# Generated by Django 5.1.6 on 2025-03-03 21:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When a user revoked access to the 3rd party integration', null=True)),
                ('scope', models.CharField(blank=True, help_text='comma delimited string, eg: "activity:read,activity:write"', max_length=255, null=True)),
                ('refresh_token', models.CharField(help_text='token to exchange for an access_token')),
                ('access_token', models.CharField(help_text='short-lived token used to make API calls on behalf of the user')),
                ('expires_at', models.PositiveIntegerField(help_text='the number of seconds since the epoch when the access_token will expire')),
                ('auto_import', models.BooleanField(default=False)),
                ('auto_export', models.BooleanField(default=False)),
                ('initial_sync', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_id', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('external_id', models.PositiveIntegerField()),
                ('activity_type', models.CharField()),
                ('duration', models.PositiveIntegerField()),
                ('distance', models.FloatField()),
                ('avg_watts', models.FloatField()),
                ('avg_speed', models.FloatField()),
                ('work_done', models.FloatField()),
                ('elev_gain', models.FloatField()),
                ('polyline', models.CharField(help_text='comes from an activities map.summary_polyline attribute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strava_draw_api.integration')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
