# Generated by Django 5.2 on 2025-04-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_draw_api', '0004_activitystream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystream',
            name='stream_type',
            field=models.CharField(unique=True),
        ),
    ]
