# Generated by Django 5.2 on 2025-04-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_draw_api', '0005_alter_activitystream_stream_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystream',
            name='stream_type',
            field=models.CharField(),
        ),
        migrations.AlterUniqueTogether(
            name='activitystream',
            unique_together={('activity', 'stream_type')},
        ),
    ]
