# Generated by Django 5.2 on 2025-04-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_draw_api', '0006_alter_activitystream_stream_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='weighted_average_watts',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
