FROM certbot/certbot:v3.3.0

# Set environment variables for Certbot
ENV CERTBOT_EMAIL=as173171@gmail.com
ENV CERTBOT_DOMAIN=routeviewer.com

# Run Certbot to obtain the certificate
# CMD ["certbot", "certonly", "--standalone", "-d", "${CERTBOT_DOMAIN}", "-m", "${CERTBOT_EMAIL}", "--agree-tos", "--non-interactive"]